---ejercitario objetos---

---ejer 1 ----
CREATE OR REPLACE TYPE T_CLIENTE AS OBJECT
( CEDULA_RUC VARCHAR2(14),
	NOMBRE VARCHAR2(40),
	APELLIDO VARCHAR2(40),
	TELEFONO VARCHAR2(40),
	DIRECCION VARCHAR2(40),
	MEMBER FUNCTION NOMBRE_COMPUESTO RETURN VARCHAR2,
	STATIC FUNCTION ASIGNAR_CLIENTE(P_CEDULA_RUC NUMBER) RETURN T_CLIENTE,
	ORDER MEMBER FUNCTION ORDEN_CLI(CLI T_CLIENTE) RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY T_CLIENTE AS
	MEMBER FUNCTION NOMBRE_COMPUESTO RETURN VARCHAR2
	IS
		BEGIN
			RETURN TRIM(NOMBRE)||' '||TRIM(APELLIDO);
		END;
	STATIC FUNCTION ASIGNAR_CLIENTE(P_CEDULA_RUC NUMBER) RETURN T_CLIENTE
	IS
		V_TIPO_CLIENTE T_CLIENTE;
		CURSOR C_CLIENTE IS	
			SELECT C.CEDULA, C.NOMBRE, C.APELLIDO, C.TELEFONO, C.DIRECCION, C.TIPO_PERSONA
			FROM B_PERSONAS C
			WHERE (CEDULA = P_CEDULA_RUC OR CEDULA = P_CEDULA_RUC) AND ES_CLIENTE = 'S';
		
		R_CLI C_CLIENTE%ROWTYPE;
		
		BEGIN
			OPEN C_CLIENTE;
			FETCH C_CLIENTE INTO R_CLI;
			CLOSE C_CLIENTE;
			V_TIPO_CLIENTE := T_CLIENTE(R_CLI.CEDULA, R_CLI.NOMBRE, R_CLI.APELLIDO,
							  R_CLI.TELEFONO, R_CLI.DIRECCION);
			RETURN V_TIPO_CLIENTE;
		END;
	
	ORDER MEMBER FUNCTION ORDEN_CLI(CLI T_CLIENTE) RETURN NUMBER
	IS
		BEGIN
			IF SELF.CEDULA_RUC < CLI.CEDULA_RUC THEN RETURN (-1);
			ELSIF SELF.CEDULA_RUC = CLI.CEDULA_RUC THEN RETURN (0);
			ELSE RETURN (1);
		END IF;
	END;
	END;
	/
	
	
	---ejemplo de ORDER en objetos con miembros---

CREATE or REPLACE TYPE tipo_clientes AS OBJECT
(cli_id NUMBER,
nombre VARCHAR2(30),
MEMBER FUNCTION ver_nombre RETURN varchar2,
ORDER MEMBER FUNCTION orden_cli (cli1 tipo_clientes)
RETURN NUMBER);
/

CREATE OR REPLACE TYPE BODY tipo_clientes IS
MEMBER FUNCTION ver_nombre RETURN varchar2 IS
BEGIN
RETURN nombre;
END;
ORDER MEMBER FUNCTION orden_cli (cli1 tipo_clientes)
RETURN NUMBER IS
BEGIN
IF cli_id < cli1.cli_id THEN RETURN (-1);
ELSIF cli_id = cli1.cli_id THEN RETURN (0);
ELSE RETURN (1);
END IF;
END;
END;
/
DECLARE
A tipo_clientes := tipo_clientes(1, 'MARIO BENEDETI');
B tipo_clientes := tipo_clientes(2, 'JOSELUCHO');
BEGIN
IF A.orden_cli(B)=1 then
dbms_output.put_line('A > B');
ELSIF A.orden_cli(B) = 0 then
dbms_output.put_line('A = B');
ELSE
dbms_output.put_line('A < B');
END IF;
IF A > B then
DBMS_OUTPUT.PUT_LINE(' A MAYOR B');
ELSE
DBMS_OUTPUT.PUT_LINE('MENOR O IGUAL');
END IF;
END;

---- ejemplo de tablas indexadas----
DECLARE
TYPE t_poblacion IS TABLE OF NUMBER INDEX BY
VARCHAR2(64);
poblacion_pais t_poblacion;
cantidad NUMBER;
BEGIN
poblacion_pais('China') := 1321000000;
poblacion_pais('EEUU') := 302750000;
poblacion_pais('Brasil') := 186990000;
DBMS_OUTPUT.PUT_LINE('El primer índice es '|| poblacion_pais.FIRST);
DBMS_OUTPUT.PUT_LINE('El primer valor es ' || poblacion_pais(poblacion_pais.FIRST));
END;
/