---TEMA4---
CREATE MATERIALIZED VIEW V_HORARIO
BUILD IMMEDIATE
REFRESH NEXT SYSDATE +6/24
AS
SELECT DISTINCT(F.NOMBRE ||' '||F.APELLIDO) FISIOTERAPEUTA,
DECODE(T.NRO_TURNO,1, P.APELLIDO, '-') "07:00",
DECODE(T.NRO_TURNO,2, P.APELLIDO, '-') "08:00",
DECODE(T.NRO_TURNO,3, P.APELLIDO, '-') "09:00",
DECODE(T.NRO_TURNO,4, P.APELLIDO, '-') "10:00",
DECODE(T.NRO_TURNO,5, P.APELLIDO, '-') "11:00",
DECODE(T.NRO_TURNO,6, P.APELLIDO, '-') "12:00",
DECODE(T.NRO_TURNO,7, P.APELLIDO, '-') "13:00",
DECODE(T.NRO_TURNO,8, P.APELLIDO, '-') "14:00",
DECODE(T.NRO_TURNO,9, P.APELLIDO, '-') "15:00",
DECODE(T.NRO_TURNO,10, P.APELLIDO, '-') "16:00",
DECODE(T.NRO_TURNO,11, P.APELLIDO, '-') "17:00",
DECODE(T.NRO_TURNO,12, P.APELLIDO, '-') "18:00"
FROM TRATAMIENTO T
	JOIN PACIENTE P 
		ON T.CEDULA=P.CEDULA
	JOIN FISIOTERAPEUTA F
		ON T.COD_FISIOTERAPEUTA = F.COD_FISIOTERAPEUTA
WHERE T.FECHA_FIN IS NULL AND TRUNC(T.FECHA_INICIO) <= TRUNC(SYSDATE);


