---TEMA 5 ---

CREATE OR REPLACE PROCEDURE P_CONSULTA_TRATAMIENTO (VALOR VARCHAR2, CRITERIO VARCHAR2, ORDEN VARCHAR2)
IS 

BEGIN
	SELECT 	V_ID_TRATAMIENTO Id_tratamiento,
			V_DESCRIPCION, 
			V_NRO_SESIONES,
			P.NOMBRE||' '||P.APELLIDO "PACIENTE(Nom y Ape)",
			H.HORA_TURNO "HORA TURNO",
			F.NOMBRE||' '||F.APELLIDO "MEDICO (Nom Y Ape)",
			
			