---TEMA4---
CREATE MATERIALIZED VIEW V_HORARIO
BUILD IMMEDIATE
REFRESH NEXT SYSDATE +6/24
AS
SELECT F.NOMBRE ||' '||F.APELLIDO FISIOTERAPEUTA,
DECODE(T.NRO_TURNO,1, P.APELLIDO, '-') "07:00"
FROM TRATAMIENTO T
	JOIN PACIENTE P 
		ON T.CEDULA=P.CEDULA
	JOIN FISIOTERAPEUTA F
		ON T.COD_FISIOTERAPEUTA = F.COD_FISIOTERAPEUTA
WHERE T.FECHA_FIN IS NULL;


