CREATE OR REPLACE PROCEDURE P_CONSULTAR_TRATAMIENTO (VALOR VARCHAR2, CRITERIO VARCHAR2, ORDEN VARCHAR2) 
IS
	TYPE T_CUR IS REF CURSOR;
	V_CUR T_CUR;
	V_ID TRATAMIENTO.ID_TRATAMIENTO%TYPE;
	V_DESC TRATAMIENTO.DESCRIPCION%TYPE;
	V_NRO_SESION TRATAMIENTO.NRO_SESIONES%TYPE;
	V_HORA_TURNO HORARIO.HORA_INICIO%TYPE;
	V_PACIENTE VARCHAR2(60);
	V_MEDICO VARCHAR2(60);
	V_CANT_EQUIPOS NUMBER(6);
	V_SENTENCIA VARCHAR2(2000):=q'[
	SELECT	DISTINCT T.ID_TRATAMIENTO AS ID,
			T.DESCRIPCION AS DESCRIPCION, 
			T.NRO_SESIONES AS NRO_SESIONES, 
			H.HORA_INICIO AS HORA_TURNO, 
			P.NOMBRE||' '||P.APELLIDO AS PACIENTE, 
			F.NOMBRE||' '||F.APELLIDO AS MEDICO, 
				(SELECT COUNT(EQ.ID_TRATAMIENTO) 
					FROM EQUIPAMIENTO_UTILIZADO EQ 
					WHERE EQ.ID_TRATAMIENTO=T.ID_TRATAMIENTO 
					GROUP BY T.ID_TRATAMIENTO) AS EQUIPOS_UTILIZADOS 
					FROM TRATAMIENTO T JOIN HORARIO H 
					ON H.NRO_TURNO=T.NRO_TURNO 
					JOIN PACIENTE P 
					ON P.CEDULA=T.CEDULA JOIN FISIOTERAPEUTA F 
					ON F.COD_FISIOTERAPEUTA=T.COD_FISIOTERAPEUTA 
					JOIN EQUIPAMIENTO_UTILIZADO EU 
					ON EU.ID_TRATAMIENTO=T.ID_TRATAMIENTO]';
BEGIN
	IF UPPER(CRITERIO)='P' THEN
		V_SENTENCIA:=V_SENTENCIA||q'[ WHERE P.NOMBRE LIKE '%]'||VALOR||q'[%']';
	ELSIF UPPER(CRITERIO)='M' THEN
		V_SENTENCIA:=V_SENTENCIA||q'[ WHERE F.NOMBRE LIKE '%]'||VALOR||q'[%']';
	ELSE			
		RAISE_APPLICATION_ERROR(-20002,'OPCION INVALIDA');
	END IF;
	IF UPPER(ORDEN)='I' THEN
		V_SENTENCIA:=V_SENTENCIA||q'[ ORDER BY T.ID_TRATAMIENTO]';
	ELSIF UPPER(ORDEN)='D' THEN
		V_SENTENCIA:=V_SENTENCIA||q'[ ORDER BY T.DESCRIPCION]';
	ELSE			
		RAISE_APPLICATION_ERROR(-20003,'OPCION INVALIDA');
	END IF;
		--IMPRIMIR PARA VERIFICAR V_SENTENCIA
		--DBMS_OUTPUT.PUT_LINE(V_SENTENCIA);
		OPEN V_CUR FOR V_SENTENCIA;
		LOOP
			FETCH V_CUR INTO V_ID,V_DESC,V_NRO_SESION,V_HORA_TURNO,V_PACIENTE,V_MEDICO,V_CANT_EQUIPOS;
			EXIT WHEN V_CUR%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE(V_ID||' '||V_DESC||' '||V_NRO_SESION||' '||V_HORA_TURNO||' '||V_PACIENTE||' '||V_MEDICO||' '||V_CANT_EQUIPOS);			
		END LOOP;
		CLOSE V_CUR;
EXCEPTION
	WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20004,SQLERRM);		
	END;
/
