CREATE OR REPLACE TRIGGER T_BI_TRATAMIENTO
FOR INSERT OR UPDATE ON TRATAMIENTO COMPOUND TRIGGER
	 
	TYPE T_TR IS TABLE OF TRATAMIENTO%ROWTYPE INDEX BY BINARY_INTEGER;
	V_TR T_TR;
    R_PACI PACIENTE%ROWTYPE;
	V_IND NUMBER;
	V_FE_FIN DATE;
	CURSOR C_TRATAMIENTOS IS SELECT * FROM TRATAMIENTO WHERE FECHA_FIN IS NULL;
	BEFORE STATEMENT IS
	 BEGIN
		V_TR.DELETE;
		FOR REG IN C_TRATAMIENTOS LOOP
			V_TR(REG.ID_TRATAMIENTO).ID_TRATAMIENTO := REG.ID_TRATAMIENTO;
			V_TR(REG.ID_TRATAMIENTO).CEDULA := REG.CEDULA;
			V_TR(REG.ID_TRATAMIENTO).NRO_TURNO := REG.NRO_TURNO;
			V_TR(REG.ID_TRATAMIENTO).COD_FISIOTERAPEUTA := REG.COD_FISIOTERAPEUTA;
            V_TR(REG.ID_TRATAMIENTO).FECHA_INICIO := REG.FECHA_INICIO;
            V_TR(REG.ID_TRATAMIENTO).FECHA_FIN := PKG_TRATAMIENTO.F_CALCULAR_FIN(REG.FECHA_INICIO, REG.NRO_SESIONES);
			END LOOP;
	END BEFORE STATEMENT;
	
BEFORE EACH ROW IS
 BEGIN
	 V_FE_FIN := PKG_TRATAMIENTO.F_CALCULAR_FIN(:NEW.FECHA_INICIO, :NEW.NRO_SESIONES);
	 V_IND := V_TR.FIRST;
	 WHILE V_IND <= V_TR.LAST LOOP
		--DBMS_OUTPUT.PUT_LINE(V_TR(V_IND).ID_TRATAMIENTO);
	    -- VERIFICA PACIENTES
	    IF INSERTING OR (UPDATING AND :NEW.ID_TRATAMIENTO <> V_IND) THEN
			IF V_TR(V_IND).CEDULA = :NEW.CEDULA AND :NEW.NRO_TURNO = V_TR(V_IND).NRO_TURNO  THEN
				IF (:NEW.FECHA_INICIO >= V_TR(V_IND).FECHA_INICIO AND :NEW.FECHA_INICIO <= V_TR(V_IND).FECHA_FIN)  OR 
				(V_FE_FIN >= V_TR(V_IND).FECHA_INICIO AND V_FE_FIN <= V_TR(V_IND).FECHA_FIN)   THEN
					RAISE_APPLICATION_ERROR(-20001,'ERROR, YA TIENE TRATAMIENTO EN ESA FECHA');
				END IF;
			END IF;
			-- VERIFICA FISIOTERAPEUTA
			IF V_TR(V_IND).COD_FISIOTERAPEUTA = :NEW.COD_FISIOTERAPEUTA AND :NEW.NRO_TURNO = V_TR(V_IND).NRO_TURNO THEN
				IF (:NEW.FECHA_INICIO >= V_TR(V_IND).FECHA_INICIO AND :NEW.FECHA_INICIO <= V_TR(V_IND).FECHA_FIN)  OR 
				(V_FE_FIN >= V_TR(V_IND).FECHA_INICIO AND V_FE_FIN <= V_TR(V_IND).FECHA_FIN)   THEN
					RAISE_APPLICATION_ERROR(-20001,'ERROR, YA TIENE TRATAMIENTO EN ESA FECHA');
				END IF;
			END IF;
		END IF;
		V_IND := V_TR.NEXT(V_IND);
	 END LOOP;
     V_TR(:NEW.ID_TRATAMIENTO).CEDULA:=:NEW.CEDULA;
     V_TR(:NEW.ID_TRATAMIENTO).COD_FISIOTERAPEUTA:=:NEW.COD_FISIOTERAPEUTA;
     V_TR(:NEW.ID_TRATAMIENTO).FECHA_INICIO:=:NEW.FECHA_INICIO;
     V_TR(:NEW.ID_TRATAMIENTO).FECHA_FIN:=V_FE_FIN;
     V_TR(:NEW.ID_TRATAMIENTO).NRO_TURNO:=:NEW.NRO_TURNO;
 EXCEPTION WHEN NO_DATA_FOUND THEN
 RAISE_APPLICATION_ERROR(-20001, 'No existe registro');

 END BEFORE EACH ROW;
END;