
CREATE TABLE ARTICULOS (
       ID                   NUMBER(8) NOT NULL,
       NOMBRE               VARCHAR2(40) NOT NULL,
       UNIDAD_MEDIDA        VARCHAR2(10) NOT NULL,
       PRECIO               NUMBER(9) DEFAULT 0 NOT NULL,
       COSTO                NUMBER(9) DEFAULT 0 NOT NULL,
       PORC_IVA             NUMBER(2) DEFAULT 0 NOT NULL,
       PORC_COMISION        NUMBER(2) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_ARTICULOS1 
              PRIMARY KEY (ID)
);

COMMENT ON TABLE ARTICULOS IS 'ARTICULOS';

CREATE TABLE CLIENTES (
       ID                   NUMBER(8) NOT NULL,
       TIPO_PERSONA         VARCHAR2(1) DEFAULT 'F' NOT NULL
                                   CONSTRAINT CK_TIPO_PERSONA15
                                          CHECK (TIPO_PERSONA IN ('F', 'J')),
       NOMBRE               VARCHAR2(40) NOT NULL,
       APELLIDO             VARCHAR2(40) NOT NULL,
       DIRECCION            VARCHAR2(40) NOT NULL,
       TELEFONO             VARCHAR2(40) NOT NULL,
       RUC                  VARCHAR2(15) NULL,
       CEDULA               VARCHAR2(15) NULL,
       CORREO_ELECTRONICO   VARCHAR2(40) NOT NULL,
       FECHA_NACIMIENTO     VARCHAR2(40) DEFAULT SYSDATE NOT NULL,
       LIMITE_CREDITO       NUMBER(9) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_CLIENTES 
              PRIMARY KEY (ID)
);

COMMENT ON TABLE CLIENTES IS 'PERSONAS(CLIENTES Y PROVEEDORES)';

CREATE TABLE CUOTAS (
      ID_VENTA             NUMBER(8) NOT NULL,
       NUMERO_CUOTA         NUMBER(8) NOT NULL,
       MONTO_CUOTA          NUMBER(9) DEFAULT 0 NOT NULL,
       VENCIMIENTO          DATE DEFAULT SYSDATE NOT NULL,
       MONTO_PAGADO         NUMBER(9) DEFAULT 0 NOT NULL,
       FECHA_CANCELA        VARCHAR2(40) NULL,
       CONSTRAINT PK_CUOTA 
              PRIMARY KEY (NUMERO_CUOTA, ID_VENTA)
);

COMMENT ON TABLE CUOTAS IS 'PLAN DE PAGOS';

CREATE TABLE INVENTARIO (
       ID_ARTICULO          NUMBER(8) NOT NULL,
       ID_LOCALIDAD         NUMBER(8) NOT NULL,
       STOCK_MINIMO         NUMBER(8) NOT NULL,
       STOCK_ACTUAL         NUMBER(8) NOT NULL,
       ULTIMA_COMPRA        DATE DEFAULT SYSDATE NULL,
       CONSTRAINT  PK_INVENTARIO 
              PRIMARY KEY (ID_LOCALIDAD, ID_ARTICULO)
);


CREATE TABLE LOCALIDAD (
       ID                   NUMBER(8) NOT NULL,
       NOMBRE               VARCHAR2(40) NOT NULL,
       CONSTRAINT PK_LOCALIDAD1 
              PRIMARY KEY (ID)
);

COMMENT ON TABLE LOCALIDAD IS 'LOCALIDAD GEOGRÁFICA';

CREATE TABLE VENDEDOR (
       CEDULA               NUMBER(11) NOT NULL,
       NOMBRE               VARCHAR2(30) NOT NULL,
       APELLIDO             VARCHAR2(30) NOT NULL,
       FECHA_ING            DATE NOT NULL,
       FECHA_NACIM          DATE NOT NULL,
       TELEFONO             VARCHAR2(15) NOT NULL,
       DIRECCION            VARCHAR2(60) NOT NULL,
       BARRIO               VARCHAR2(100) NOT NULL,
       CONSTRAINT PK_VENDEDOR 
              PRIMARY KEY (CEDULA)
);

COMMENT ON TABLE VENDEDOR IS 'EMPLEADOS (VENDEDORES)';

CREATE TABLE VENTAS (
       ID                   NUMBER(8) NOT NULL,
       NUMERO_FACTURA       NUMBER(8) NOT NULL,
       FECHA                DATE DEFAULT SYSDATE NOT NULL,
       MONTO_TOTAL          NUMBER(9) DEFAULT 0 NOT NULL,
       IVA_05               VARCHAR2(40) NOT NULL,
       IVA_10               NUMBER(9) DEFAULT 0 NOT NULL,
       PLAZO                NUMBER(2) NOT NULL,
       TIPO_VENTA           VARCHAR2(2) DEFAULT 'CO' NOT NULL
                                   CONSTRAINT CK_CONT_CR13
                                          CHECK (TIPO_VENTA IN ('CR', 'CO')),
       CEDULA_VENDEDOR      NUMBER(11) NOT NULL,
       ID_CLIENTE           NUMBER(8) NOT NULL,
       ID_LOCALIDAD         NUMBER(8) NOT NULL,
       CONSTRAINT PK_VENTA1 
              PRIMARY KEY (ID)
);

COMMENT ON TABLE VENTAS IS 'VENTAS REALIZADAS';

CREATE TABLE VENTAS_DETALLE (
       ID_VENTA             NUMBER(8) NOT NULL,
       NUMERO_ITEM          VARCHAR2(40) NOT NULL,
       ID_ARTICULO          NUMBER(8) NOT NULL,
       CANTIDAD             NUMBER(8) NOT NULL,
       PRECIO               NUMBER(9) DEFAULT 0 NOT NULL,
       TOTAL                NUMBER(9) DEFAULT 0 NOT NULL,
       IVA                  NUMBER(9) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_DETALLE_VENTA1 
              PRIMARY KEY (NUMERO_ITEM, ID_VENTA)
);

COMMENT ON TABLE VENTAS_DETALLE IS 'DETALLE DE LAS VENTAS REALIZADAS';

ALTER TABLE CUOTAS
       ADD  ( CONSTRAINT R_VENTA_CUOTA
              FOREIGN KEY (ID_VENTA)
                             REFERENCES VENTAS ) ;


ALTER TABLE INVENTARIO
       ADD  ( CONSTRAINT R_ARTIC_LOCAL
              FOREIGN KEY (ID_ARTICULO)
                             REFERENCES ARTICULOS ) ;


ALTER TABLE INVENTARIO
       ADD  ( CONSTRAINT R_LOCAL_ART
              FOREIGN KEY (ID_LOCALIDAD)
                             REFERENCES LOCALIDAD ) ;


ALTER TABLE VENTAS
       ADD  ( CONSTRAINT R_LOCALIDAD_VENTA
              FOREIGN KEY (ID_LOCALIDAD)
                             REFERENCES LOCALIDAD ) ;


ALTER TABLE VENTAS
       ADD  ( CONSTRAINT R_CLIENTE_VENTA1
              FOREIGN KEY (ID_CLIENTE)
                             REFERENCES CLIENTES ) ;


ALTER TABLE VENTAS
       ADD  ( CONSTRAINT R_VENDEDOR_VENTA1
              FOREIGN KEY (CEDULA_VENDEDOR)
                             REFERENCES VENDEDOR ) ;


ALTER TABLE VENTAS_DETALLE
       ADD  ( CONSTRAINT R_ART_VENTAS
              FOREIGN KEY (ID_ARTICULO)
                             REFERENCES ARTICULOS ) ;


ALTER TABLE VENTAS_DETALLE
       ADD  ( CONSTRAINT R_VENTA_ARTICULOS
              FOREIGN KEY (ID_VENTA)
                             REFERENCES VENTAS ) ;

