DECLARE
	CURSOR C_VENTAS IS
	SELECT v.id_articulo, a.nombre, v.cantidad
	FROM b_Detalle_ventas v JOIN b_Ventas c
	ON c.id = v.id_venta JOIN b_articulos a
	ON a.id = v.id_articulo
	WHERE TRUNC(c.fecha) = TO_DATE('02/01/2011','DD/MM/YYYY');
BEGIN
	FOR R_VENTAS IN C_VENTAS LOOP -- No hacer OPEN ni FETCH!!
	DBMS_OUTPUT.PUT_LINE (R_VENTAS.NOMBRE||'-
	'||TO_CHAR(R_VENTAS.CANTIDAD, '999G999'));
	END LOOP; --No hacer el CLOSE
END;

DECLARE 
	CURSOR C_CLIENTES
	
SELECT V.ID_CLIENTE, P.NOMBRE||' '||P.APELLIDO NOMBRE,
	SUM(V.MONTO_TOTAL) TOT_VENTAS
FROM B_VENTAS V JOIN B_PERSONAS P
	ON P.ID = V.ID_CLIENTE
	WHERE P.ID_LOCALIDAD = PID --Por cada localidad.
GROUP BY V.ID_CLIENTE, P.NOMBRE||' '||P.APELLIDO;	

DECLARE
 CURSOR C_CLIENTES(PID NUMBER) IS
SELECT V.ID_CLIENTE, P.NOMBRE||' '||P.APELLIDO NOMBRE,
	SUM(V.MONTO_TOTAL) TOT_VENTAS
FROM B_VENTAS V JOIN B_PERSONAS P
	ON P.ID = V.ID_CLIENTE
	WHERE P.ID_LOCALIDAD = P.ID --Por cada localidad.
GROUP BY V.ID_CLIENTE, P.NOMBRE||' '||P.APELLIDO
BEGIN	DOR R_LOC IN (SELECT * FROM B_LOCALIDAD) LOOP
		DBMS_OUTPUT.PUT_LINE('LOCALIDAD'||R_LOC.ID);
		FORM R_CLI IN C_CLIENTES(R_LOC.ID) LOOP	
			DBMS_OUTPUT.PUT_LINE('CLIENTE'||R_CLI.NOMBRE||'VENTA:'||TO_CHAR(R_CLI.TOT_VENTAS));
			END LOOP;
		END LOOP;
END;

DECLARE
V_ID C_EMP IS
	SELECT P.CEDULA, C.ASIGANACION
	FROM B_POSICION_ACTUAL P JOIN
	B_Categorias_salariale CACHE_INSTANCES	
	ON C.COD_CATEGORIA = P.COD_CATEGORIA
	WHERE P.FECHA

BEGIN
	SELECT NVL(MAX(ID)) INTO V_ID
	FROM B_LIQUIDACION;
	V_ID := NVL(V_ID,0) + 1;
	INSERT INTO B_LIQUIDACION VALUES
	(							);