CREATE TABLE ASISTENCIA ( 
ID NUMBER(12) PRIMARY KEY NOT NULL,
CEDULA NUMBER (11) NOT NULL,
HORA_ENTRADA DATE NOT NULL,
HORA_SALIDA DATE NOT NULL,
CONSTRAINT FK_ASIST_CEDULA FOREIGN KEY (CEDULA) REFERENCES
B_EMPLEADOS(CEDULA)
);

ALTER TABLE ASISTENCIA 
ADD CONSTRAINT CK_HORA_SAL 
CHECK((HORA_SALIDA IS NULL) OR ((HORA_SALIDA > HORA_ENTRADA) 
AND (TRUNC(HORA_SALIDA) = TRUNC(HORA_ENTRADA))));

CREATE TABLE DEPENDIENTES(
CEDULA_DEPEN NUMBER(11) NOT NULL,
CEDULA NUMBER(11),
NOMBRE VARCHAR2(20) NOT NULL,
APELLIDO VARCHAR2(40) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
FECHA_ACTUALIZ DATE NULL
);

ALTER TABLE DEPENDIENTES
ADD  ( CONSTRAINT FK_DEPEN_CEDULA PRIMARY KEY (CEDULA_DEPEN, CEDULA) ) ;


CREATE TABLE LEGAJO (
ID NUMBER(8) NULL,
DESCRIPCION_EVENTO VARCHAR2 (500) NOT NULL,
TIPO_EVENTO VARCHAR2(2) NOT NULL,
FECHA_EVENTO DATE NOT NULL,
DURACION NUMBER(3) NOT NULL,
CEDULA NUMBER(11) NOT NULL,
CONSTRAINT FK_LEGAJO_CEDULA FOREIGN KEY (CEDULA) REFERENCES
B_EMPLEADOS(CEDULA)
);


