--11/04/2019
--Programas o PL SQL nombrados
-- en la cabecera se define el ombre del sub-programa, tipo y argumentos
--No se especifica la longitud del tipo de dato
`
-- El declare no se escribe 

-- ejemplo 

CREATE  OR REPLACE PROCEDURE PP IS
	V_FECHA DATE;
BEGIN
	V_FECHA:= SYSDATE;
	DBMS_OUTPUT.PUT_LINE(V_FECHA);
END;
/

SET SERVEROUTPUT ON
EXECUTE PP

-- DENTREO DE P

BEGIN
	PP
DECLARE
END;

CREATE  OR REPLACE PROCEDURE PP 
	(PFEC IN DATE, PDIA OUT VARCHAR2)
	IS
BEGIN
	V_FECHA:=TO_CHAR(PFEC,'DAY');
	DBMS_OUTPUT.PUT_LINE(V_FECHA);
END;
/

SHOW ERRORS


CREATE OR REPLACE FUNCTION 
DEDUCCION(PID_VENTA NUMBER) RETURN 
NUMBERISV_DEDUCCION NUMBER;
BEGINSELECT SUM(ROUND(V.PRECIO * A.PORC_IVA)) INTO 
V_DEDUCCIONFROM B_DETALLE_VENTAS V JOIN
 B_ARTICULOS AON   A.ID  = V.ID_ARTICULOWHERE V.ID_VENTA = PID_VENTA;
 RETURN 
 V_DEDUCCION;
 END;